#!/bin/bash

for f in *.mp4; do
  ffmpeg -i "$f" \
  -vf "scale=480:272:force_original_aspect_ratio=decrease,pad=480:272:(ow-iw)/2:(oh-ih)/2" \
  -c:v libx264 -profile:v baseline -level 3.0 -b:v 1200k -r 30 \
  -c:a aac -b:a 128k \
  "${f%.*}_psp.mp4"
done
